config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # index
  get "restaurants", to: 'restaurants#index'
  # new
  get 'restaurants/new', to: 'restaurants#new'
  # create
  post 'restaurants', to: 'restaurants#create'
  # edit
  get 'restaurants/:id/edit', to: 'restaurants#edit'
  # update
  patch 'restaurants/:id', to: 'restaurants#update'
  # show
  get 'restaurants/:id', to: 'restaurants#show', as: :restaurant
  # destroy
  delete 'restaurants/:id', to: 'restaurants#destroy'

  # resources :restaurants
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [ :show, :edit, :update, :destroy ]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    restaurant = Restaurant.new(restaurant_params)
    restaurant.save
    redirect_to restaurant_path(restaurant)
  end

  def edit
  end

  def update
    # raise
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  # strong params
  def restaurant_params
    params.require(:restaurant).permit(:name, :rating, :address)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThespoonWithActiverecord605</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :rating %>
  <%= f.number_field :rating %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<h1>Here are all the restaurants</h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= restaurant.name %> | <%= link_to "More info", restaurant_path(restaurant) %>
      <%= link_to "Delete", restaurant_path(restaurant), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary" %>
    </li>
  <% end %>
</ul>


<%= link_to "Add a new restaurant", restaurants_new_path %>

app/views/restaurants/new.html.erb
<h1>Add a restaurant</h1>

<%= render "form", restaurant: @restaurant %>


<!-- <form action="">
  <label for="name">Name</label>
  <input type="text" id="name">
</form> -->

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<p>Address: <%= @restaurant.address %></p>
<p>Stars: <%= @restaurant.rating %></p>

<%= link_to "Back to all restaurants", restaurants_path %>